server:
  port: 8080

#mybatis:
#  mapper-locations:
#    - classpath:mapper/*.xml
#    - classpath*:com/**/mapper/*.xml

#h2
spring:
  mail:
    host: smtp.163.com
    username: wsbynss@163.com
    password: by199504175533
    protocol: smtp
    default-encoding: utf-8
  jpa:
    show-sql: true
    hibernate:

      ddl-auto: update
    database: mysql
  #    database: h2

  datasource:
    url: jdbc:mysql://192.168.173.209:3307/demo20200611?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  ########## h2shu数据库配置 #########################
#    url: jdbc:h2:mem:sapjcodemo
#    driverClassName: org.h2.Driver
#    username: sa
#    password: sa
##    schema: classpath:db/schema.sql
##    data: classpath:db/data.sql
#    platform: h2
#
#  h2:
#    console:
#      settings:
#        web-allow-others: true
#      path: /h2
#      enabled: true
  #################################################

  redis:
    host: 192.168.173.209
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1
    password: redis
